###############################
###POISSON REGRESSION MODEL ###
###############################
## Author: Arnau Escapa
## Data: Gener 2018

##Data Generator
n <- 300
#x  uniformly randomt 1 to 20 (positive!)
x <- sort(runif(n = n, min = 1, max =20))
b0 <- 0.5
b1<-0.5
lam=b0+b1*x
#Sample y values
y <- rpois(n=n, lambda=lam)
dat <- data.frame(y,x)
data.pois <- dat

###we will simulate the data that we actually have to check performance. 
fitted <- subset(dat, select=c(x,y))
fitted$y <- NA

##and  all X-range to make the nice plot of confidence region
newdata <- expand.grid(x=seq(min(data.pois$x), max(data.pois$x), len=100), y=NA)
dat.pred <- rbind(dat,fitted,newdata)

#fit the model
library(INLA)
dat.inla <- inla(y~x, family='poisson',
                 data=dat.pred,
                 control.predictor=list(link=1, compute=TRUE),
                 control.compute=list(dic=TRUE, cpo=TRUE, waic=TRUE))
dat.inla$summary.fixed
##Real values: b0=0.5 b2=0.5


###PREDICTIONS
newdata <- cbind(newdata,dat.inla$summary.fitted.values[(nrow(dat)+nrow(fitted)+1):nrow(dat.pred),])
head(newdata)

newdata <- reshape:::rename(newdata, c("0.025quant"="lower", "0.975quant"="upper"))

library(ggplot2)
ggplot(newdata, aes(y=mean, x=x)) +
  geom_blank()+
  geom_point(data=data.pois, aes(y=y, x=x)) +
  geom_ribbon(aes(ymin=lower, ymax=upper), fill='blue', alpha=0.2) +
  geom_line() +
  theme_classic()+
  theme(legend.key.width=unit(2,'lines'), legend.position=c(0,1), legend.justification=c(0,1))

###One may change the work "poisson" for any other exponential distribution
##(i.e Beta,Gamma, Binomial, InverseGamma,) and it should work! However note that the current data is generated by a Poisson distribution.


### Last SECOND improvement not explained in the memory. 
#### I just find out, we can improve the results using log scale. This is considering lam_i=log(y_i) but we must tell it to the INLA somehow.###
########

##Data Generator
n <- 50
x <- sort(runif(n = n, min = 1, max =20))

b0 <- 0.15
b1<-0.075
lam=exp(b0+b1*x) ###!!!! Danger--It it true that:  Poiss(e(x))=y <--> Poiss(x)=log(y)

y <- rpois(n=n, lambda=lam)
dat <- data.frame(y,x)
data.pois <- dat

###we will simulate the data that we actually have to check performance. 
fitted <- subset(dat, select=c(x,y))
fitted$y <- NA

##and  all X-range to make the nice plot of confidence region
newdata <- expand.grid(x=seq(min(data.pois$x), max(data.pois$x), len=100), y=NA)
dat.pred <- rbind(dat,fitted,newdata)

#fit the model
library(INLA)
dat.inla <- inla(y~x, family='poisson',
                 data=dat.pred,
                 control.family=list(link='log'), ###we tell the model we use log scale
                 control.predictor=list(link=1, compute=TRUE),
                 control.compute=list(dic=TRUE, cpo=TRUE, waic=TRUE) )
dat.inla$summary.fixed
##Real values: b0=0.15 b2=0.075 ###WORKS MUCH BETTER!


###PREDICTIONS
newdata <- cbind(newdata,dat.inla$summary.fitted.values[(nrow(dat)+nrow(fitted)+1):nrow(dat.pred),])
head(newdata)

newdata <- reshape:::rename(newdata, c("0.025quant"="lower", "0.975quant"="upper"))

library(ggplot2)
ggplot(newdata, aes(y=mean, x=x)) +
  geom_blank()+
  geom_point(data=data.pois, aes(y=y, x=x)) +
  geom_ribbon(aes(ymin=lower, ymax=upper), fill='blue', alpha=0.2) +
  geom_line() +
  theme_classic()+
  theme(legend.key.width=unit(2,'lines'), legend.position=c(0,1), legend.justification=c(0,1))

